export const GET_ALL_CATEGORY ="GET_ALL_CATEGORY"
export const GET_ERROR ="GET_ERROR"
export const CREATE_CATEGORY ="CREATE_CATEGORY"
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY'

export const CREATE_SUB_CATEGORY ="CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'

export const CREATE_BRAND ="CREATE_BRAND"
export const GET_ALL_BRAND ="GET_ALL_BRAND"
export const GET_ONE_BRAND ="GET_ONE_BRAND"


export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const GET_PRODUCT_LIKE = 'GET_PRODUCT_LIKE'
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'


export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const VERIFY_PASSWORD = 'VERIFY_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'

export const CREATE_REVIEW = 'CREATE_REVIEW'
export const ALL_REVIEW_PRODUCT = 'ALL_REVIEW_PRODUCT'
export const DELETE_REVIEW = 'DELETE_REVIEW'
export const UPDATE_REVIEW = 'UPDATE_REVIEW'



export const ADD_TO_WISH_LIST = 'ADD_TO_WISH_LIST'
export const REMOVE_FROM_WISH_LIST = 'REMOVE_FROM_WISH_LIST'
export const USER_WISH_LIST = 'USER_WISH_LIST'



export const ADD_COUPON = 'ADD_COUPON'
export const GET_ALL_COUPON = 'GET_ALL_COUPON'
export const DELETE_COUPON = 'DELETE_COUPON'
export const GET_ONE_COUPON = 'GET_ONE_COUPON'
export const EDIT_COUPON = 'EDIT_COUPON'



export const ADD_USER_ADRESS = 'ADD_USER_ADRESS'
export const ALL_USER_ADRESS = 'ALL_USER_ADRESS'
export const DELETE_USER_ADRESS = 'DELETE_USER_ADRESS'
export const ONE_USER_ADRESS = 'ONE_USER_ADRESS'
export const EDIT_USER_ADRESS = 'EDIT_USER_ADRESS'


export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD'

export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_ALL_USER_CART = 'GET_ALL_USER_CART'
export const CLEAR_ALL_USER_CART = 'CLEAR_ALL_USER_CART'
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART'
export const UPDATE_ITEM_CART = 'UPDATE_ITEM_CART'
export const APPLY_COUPON_CART = 'APPLY_COUPON_CART'
export const GET_ALL_PRODUCT_CATEGORY = 'GET_ALL_PRODUCT_CATEGORY'
export const GET_ALL_PRODUCT_BRAND = 'GET_ALL_PRODUCT_BRAND'


export const CREATE_ORDER_CASH = 'CREATE_ORDER_CASH'
export const CREATE_ORDER_CARD = 'CREATE_ORDER_CARD'

export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const GET_ONE_ORDERS = 'GET_ONE_ORDERS'
export const UPDATE_ORDER_PAY = 'UPDATE_ORDER_PAY'
export const UPDATE_ORDER_DELIVER = 'UPDATE_ORDER_DELIVER'
